# Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [26]:
b = []
y = -1
a = list(range(int(input('Введите количество элементов для создания numpy array: '))))
for x in a:
    b.append(a[y])
    y -=1
result = np.array(b)
result

Введите количество элементов для создания numpy array: 10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [10]:
N = int(input('Введите количество элементов для создания numpy array: '))
result = np.array(list(reversed([i for i in range(0,N)])))
result

Введите количество элементов для создания numpy array: 10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [12]:
diag_mat = np.diag(result)
print(diag_mat)
print(f'Сумма элементов матрицы, расположенных на диагонали: {np.trace(diag_mat)}')

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
Сумма элементов матрицы, расположенных на диагонали: 45


# Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [38]:
a_ = np.array([ [4, 2, 1], [1, 3, 0], [0, 5, 4] ])
b_ = np.array( [4, 12, -3] )

In [14]:
from numpy import linalg

In [39]:
a_, b_

(array([[4, 2, 1],
        [1, 3, 0],
        [0, 5, 4]]),
 array([ 4, 12, -3]))

In [40]:
linalg.solve(a_,b_)

array([ 0.46666667,  3.84444444, -5.55555556])

In [41]:
np.allclose( np.dot(a_, linalg.solve(a_, b_)), b_ )

True

# Задание 4

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [42]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [43]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Рассчитаем скалярное произведение векторов (попарно произведем расчет, вектор каждого имеющего клиента с вектором нового клиента 

In [66]:
result = [0]
next_user_Length = np.linalg.norm( next_user_stats )

for user in users_stats:
    user_Length = np.linalg.norm( user )    
    if (np.dot( user, next_user_stats) / (user_Length * next_user_Length)) >= result[-1]:
        result.append(np.dot( user, next_user_stats) / (user_Length * next_user_Length))

for num, user in enumerate(users_stats):
    user_Length = np.linalg.norm( user )    
    if (np.dot( user, next_user_stats) / (user_Length * next_user_Length)) == result[-1]:
        print(f'{num}, {user}, Наиболее соответствующий пользователь')


    

7, [0 1 1 0 0 0], Наиболее соответствующий клиент
